title: Verne Tech
description: Verne Tech tips!
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://vernetech.github.io/newsletter/

aux_links:
  VTG on Github: https://github.com/vernetech/newsletter

search_enabled: true
search.button: true

search.previews: 3 -- default

collections:
  ciber:
    permalink: "/:collection/:path/"
    output: true
  otros:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    ciber:
      name: Ciberseguridad
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    otros:
      name: Otros
      nav_exclude: false
      nav_fold: false
      search_exclude: false


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  highlight-green:
    color: green
  note:
    title: üö© Note
    color: yellow
  tip:
    title: üí° Tip
    color: blue
  important:
    title: ‚ú® Important
    color: blue
  warning:
    title: ‚ö†Ô∏è Warning
    color: red
  new:
    title: üÜï New
    color: purple

mermaid:
  version: '10.3.1'



last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


