title: Verne Tech newsletter
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  newsletter on Github: https://github.com/vernetech/newsletter

collections:
  ciber:
    permalink: "/:collection/:path/"
    output: true
  otros:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    ciber:
      name: Ciberseguridad
      nav_fold: true
    otros:
      name: Otros
      nav_fold: false

relative_links:
  enabled: true
  collections: true


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  highlight-green:
    color: green
  note:
    title: ğŸš© Note
    color: yellow
  tip:
    title: ğŸ’¡ Tip
    color: blue
  important:
    title: âœ¨ Important
    color: blue
  warning:
    title: âš ï¸ Warning
    color: red
  new:
    title: ğŸ†• New
    color: purple

  
mermaid:
  version: '10.3.1'